name: PR
on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
          scope: "@jamesadcock"
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint:check

      - name: prettier
        run: "npm run prettier:check"

      - name: test
        run: npm test

      - name: build
        run: npm run build
